#!/usr/bin/perl -Tw
use HTML::Mason;

use strict; 
my $comproot = "/proj/wetter/software/serial/wth/wth_foundation/wth/trunk/mason/";
my $dataroot = "/proj/wetter/software/serial/wth/wth_foundation/wth/trunk/mason/data";
my $outbuf;

my $interp = new HTML::Mason::Interp ( comp_root  =>$comproot, 
                                       data_dir   =>$dataroot, 
                                       out_method =>\$outbuf,
                                       allow_globals => [ '%fetchopts', '%extraopts'],
                                       use_strict => 0);

#my $retval = $interp->exec('/rrdfetch', rrd=>'PressureI', start=>'-86400');
my $retval = $interp->exec('/rrdfetch', rrd=>'Indoorsensor', ds =>'Pressure');
#my $retval = $interp->exec('/rrdfetch', rrd=>'PressureI', ds =>'PressureI');
print $outbuf;
