#!/usr/bin/perl


#
#
#

use strict;

my $return;
my $variable1;
my @myarray1 = ();

my $configfile = "usingdo.conf";

unless ( $return = do $configfile)  {
  warn "Couldn't parse configfile: $configfile: $@"   if $@;
  warn "Couldn't do configfile: $configfile: $!"      unless defined $return;
  warn "Couldn't run configfile: $configfile"         unless $return;
} 

print "--- usingdo ---\n";
print "variable1: \"$variable1\"\n";
print "myarray1 : \"@myarray1\"\n";
