#!/bin/sh

#
# display rrd data 
#

# using dc to calculate pressure using international höhenformel
# echo "6 k 1 454 288 / 0.00651 * - _5.255 ^ p" |dc
#
START="`date +%s`"
DAY=86000
WEEK=604800
MONTH=18144000

RRDTOOL="/usr/bin/rrdtool"
VIEWER="/usr/bin/display"

#if [ $# -ne 3 ]; then
#	echo "Usage: rrdgraph <starttime> <rrdfile> <name>"
#	exit 1
#fi

#$RRDTOOL graph t4.gif --start $1 DEF:mytemp=$2:$3:AVERAGE LINE2:mytemp#FF0000

#$VIEWER t4.gif
#rm t4.gif

START="`echo $START $DAY - p |dc`"
echo "START: $START"

$RRDTOOL graph pressure.png \
  --start $START \
  --title "Air Pressure" \
  DEF:pressure=/proj/wetter/logs/sens20.rrd:press:AVERAGE \
  CDEF:nnpress=1.055615,pressure,* \
  LINE2:nnpress#00a000:"Atmospher ic Pressure"  \
  --lower-limit 960 --upper-limit 1060 --rigid  \
  --y-grid 5:2 \
  --units-exponent 0, \
  --height 200

#$VIEWER pressure.png

