#!/usr/bin/perl

#
#
#
use strict;

my ( $sensor_no, $sensor_type, $sensor_stat);
my ( $dataset_no, $meas_tim, $meas_sign, $meas_value);

my $LOGFILE="/proj/wetter/logs/wthlog";
my $DBFILE="/proj/wetter/logs/ws2000.db";

open LOGFH,"<$LOGFILE"
  or die "Can't open logfile \"$LOGFILE\"";


my $start = time();
my $i=0;
while ( <LOGFH> ) {

  if ( /^\d+/ ) {
    ( $sensor_no, $sensor_type, $sensor_stat, $dataset_no, 
      $meas_tim, $meas_sign, $meas_value) = split;

    print $sensor_no, $sensor_type, $sensor_stat, "\n";
    $i++;
  }
  if ( $i == 100 ) {
    exit;
  }
}

my $end = time();
print "Program started: ", scalar localtime($start), "\n";
print "Program ended:   ", scalar localtime($end), "\n";
print "Datasets processed: $i\n";